### ISSUE TITLE
Sites vs project dir. 

### ISSUE THREAD

**Issue by hans2103** [wingsuitist/brewamp#1]
One question though regarding the tutorial from Alan Ivey and I was hoping you could help me out. 
https://echo.co/blog/os-x-1010-yosemite-local-development-environment-apache-php-and-mysql-homebrew

situation according to your tutorial:

```
~/Sites/project -> http://project.dev
```

But I would like to change that a bit

```
~/Sites/project/htdocs -> http://project.dev
```

How can I change the config that it will show the content of htdocs when accessing the domain project.dev?

Using htdocs will give me the opportunity to create the entire project in `~/Sites/project`

```
~/Sites/project/bin
~/Sites/project/.modman

~/Sites/project/backup
~/Sites/project/htdocs
~/Sites/project/.git
```

**Comment by wingsuitist** [comment]
If you change this  in httpd-vhosts.conf (there are two places) it should work:

`/VirtualDocumentRoot /LocalSites/%-2+/htodcs`
